### ISSUE TITLE
Report checklist

### ISSUE THREAD

**Issue by josephholler** [samroubin/VTPharmacy#8]
- [x] Consolidate working code into one main python notebook
- [x] Export figures for powerpoints to `results/figures` 
- [x] Delete any extraneous code / data
- [x] Update `procedure_index.csv` 
- [x] Double check data metadata and `data_index.csv`
- [x] Verify ability to download private files from OSF, possibly to include use of `osfclient` <https://osfclient.readthedocs.io/>
- [x] Rerun or at least remove the check on road speed limits now that the network has expanded-- one thought is to add a boolean variable for checking speed data or not, and use that to skip over the slow data checks using *if* statements.
